#!/bin/bash

# Print message and exit with code 1
# Arguments:
#   <MESSAGE TO PRINT>
fail () {
	echo "$@"
	exit 1
}

[ $# -ne 1 ] && fail "USAGE: $0 <file>"

# Check if given file exists
[ -f "$1" ] || fail "${1}: file not found"

FILE="$1"
FILE_TMP="${FILE}.git-split"

# Create temporary copy of the given file and revert unstaged changes in the
# original. Do so only if the temporary file doesn't exist.
[ -f "${FILE_TMP}" ] || (cp "${FILE}" "${FILE_TMP}" && git checkout -- "${FILE}")

# Let user compare and apply some changes using meld
meld "${FILE}" "${FILE_TMP}"

# Remove temporary file if all changes applied to the original
diff -q "${FILE}" "${FILE_TMP}" &> /dev/null && rm "${FILE_TMP}"
