#!/bin/bash

[ $# -ne 1 ] && echo "USAGE: $0 <file>" && exit 1

# Check if meld is installed
which meld || (echo """
'meld' is not installed and is necessarry for this script to work.
Please install it on your system:
$ sudo apt-get install meld
""" && exit 1)

FILE="$1"
FILE_TMP="${FILE}.git-split"

# Create temporary copy of the given file and revert unstaged changes in the
# original. Do so only if the temporary file doesn't exist.
[ -f "${FILE_TMP}" ] || (cp "${FILE}" "${FILE_TMP}" && git checkout -- "${FILE}")

# Let user compare and apply some changes using meld
meld "${FILE}" "${FILE_TMP}"

# Remove temporary file if all changes applied to the original
diff -q "${FILE}" "${FILE_TMP}" &> /dev/null && rm "${FILE_TMP}"
